import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  checkReleaseVersions,
  readReleaseVersions,
} from "./check-release-version.mjs";

// A trimmed Cargo.lock: a sibling crate before ajax-cli, so a test that passes
// proves the matcher keys on the package name and not on file position.
const lock = (version) => `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "ajax-core"
version = "0.11.0"
dependencies = [
 "serde",
]

[[package]]
name = "ajax-cli"
version = "${version}"
dependencies = [
 "ajax-core",
]
`;

function fixture({
  manifest = "1.2.3",
  versionTxt = "1.2.3",
  cargoToml = "1.2.3",
  cargoLock = "1.2.3",
} = {}) {
  const root = mkdtempSync(join(tmpdir(), "ajax-release-"));
  mkdirSync(join(root, "crates", "ajax-cli"), { recursive: true });

  writeFileSync(
    join(root, ".release-please-manifest.json"),
    `{\n  ".": "${manifest}"\n}\n`,
  );
  writeFileSync(join(root, "version.txt"), `${versionTxt}\n`);
  writeFileSync(
    join(root, "crates", "ajax-cli", "Cargo.toml"),
    `[package]\nname = "ajax-cli"\nversion = "${cargoToml}"\nedition = "2021"\n\n[dependencies]\nversion = "not-a-version"\n`,
  );
  writeFileSync(join(root, "Cargo.lock"), lock(cargoLock));

  return root;
}

test("reads the ajax-cli version from all four files", () => {
  assert.deepEqual(readReleaseVersions(fixture()), {
    ".release-please-manifest.json": "1.2.3",
    "version.txt": "1.2.3",
    "crates/ajax-cli/Cargo.toml": "1.2.3",
    "Cargo.lock": "1.2.3",
  });
});

test("passes when every file agrees", () => {
  assert.deepEqual(checkReleaseVersions(fixture()), []);
});

for (const field of [
  "manifest",
  "versionTxt",
  "cargoToml",
  "cargoLock",
]) {
  test(`fails when only ${field} is bumped`, () => {
    const problems = checkReleaseVersions(fixture({ [field]: "1.2.4" }));
    assert.ok(problems.length > 0, `${field} drift must be reported`);
    assert.match(problems[0], /mismatch/);
    assert.ok(
      problems.some((p) => p.includes("1.2.4")),
      "report must name the odd version out",
    );
  });
}

test("fails when a version cannot be found at all", () => {
  const root = fixture();
  writeFileSync(join(root, "Cargo.lock"), lock("1.2.3").replace("ajax-cli", "ajax-cli-renamed"));
  assert.match(checkReleaseVersions(root).join("\n"), /Cargo\.lock: no ajax-cli version found/);
});

test("does not match a [dependencies] key named version", () => {
  // The Cargo.toml fixture has `version = "not-a-version"` under
  // [dependencies]; the [package] section must win.
  assert.equal(
    readReleaseVersions(fixture())["crates/ajax-cli/Cargo.toml"],
    "1.2.3",
  );
});

test("the real repository is self-consistent", () => {
  const root = join(import.meta.dirname, "..");
  assert.deepEqual(checkReleaseVersions(root), []);
});
